#!/bin/sh

# Set these paths appropriately

BIN=/home/alex/work/SIEN/SIEN-ad-matching/misc-resources/TreeTagger/bin
CMD=/home/alex/work/SIEN/SIEN-ad-matching/misc-resources/TreeTagger/cmd
LIB=/home/alex/work/SIEN/SIEN-ad-matching/misc-resources/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
