#!/bin/sh

# Set these paths appropriately

BIN=/home/alex/work/SIEN/SIEN-ad-matching/misc-resources/TreeTagger/bin
CMD=/home/alex/work/SIEN/SIEN-ad-matching/misc-resources/TreeTagger/cmd
LIB=/home/alex/work/SIEN/SIEN-ad-matching/misc-resources/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
